MVC Basics 1/Models/CreatePersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Models
{
    public class CreatePersonViewModel
    {
        [Required(ErrorMessage = "Full Name is mandatory"), MinLength(5), MaxLength(20)]
        [Display(Name = "Full Name")]
        [DataType(DataType.Text)]
        public string FullName { get; set; }

        //[Required(ErrorMessage = "Please enter city."), MinLength(3), MaxLength(15)]
        //[Display(Name = "City")]
        //[DataType(DataType.Text)]
        //public string City { get; set; }

        [Required(ErrorMessage = "Phone number is mandatory")]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        //public int CityId { get; set; }

        //public CityModel PersonCity { get; set; }

        //[Required]
        //public List<int> Languages { get; set; }

        //[Display(Name = "Country")]
        //[Required(ErrorMessage = "Select a country")]
        //public int CountryID { get; set; }

        [Display(Name = "City")]
        [Required(ErrorMessage = "Select a city")]
        public int CityID { get; set; }

        public string City { get; set; }

        [Required(ErrorMessage = "Please enter email.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email Format semms to be wrong")]
        [Display(Name = "Email")]
        public string Email { get; set; }
    }
}

MVC Basics 1/Models/PeopleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Models
{
    public class PeopleViewModel : CreatePersonViewModel
    {
        public List<Person> PersonList { get; set; }
        public string FilterString { get; set; }
        public PeopleViewModel()
        {
            PersonList = new List<Person>();
        }
    }
}

MVC Basics 1/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Models
{
    public class Person
    {
        private readonly int _personId;
        public int PersonId { get { return _personId; } }
        public string FullName { get; set; }
        public string City { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

        public Person(int _personId, string fullName, string city, string phoneNumber, string email)
        {
            this._personId = _personId;
            FullName = fullName;
            City = city;
            PhoneNumber = phoneNumber;
            Email = email;
        }
    }
}

MVC Basics 1/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC_Basics_1.Data;
using MVC_Basics_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class PeopleController : Controller
    {
        
         public IActionResult Index()
         {
             PeopleMemory peopleMemory = new PeopleMemory();
             PeopleViewModel peopleView = new PeopleViewModel() { PersonList = peopleMemory.Read() };
             if (peopleView.PersonList.Count == 0 || peopleView.PersonList == null)
             {
                 peopleMemory.SeedPeople();
             }
             return View(peopleView);
         }

         [HttpPost]
         public IActionResult Index(string filterString)
         {
             PeopleMemory peopleMemory = new PeopleMemory();
             PeopleViewModel filterPersonView = new PeopleViewModel();
             filterPersonView.PersonList = new List<Person>();
             if (filterString == "" || filterString == null)
             {
                 filterPersonView.PersonList = peopleMemory.Read();
             }
             else
             {
                 foreach (var person in peopleMemory.Read())
                 {

                     if (person.FullName.Contains(filterString, StringComparison.OrdinalIgnoreCase) || person.City.Contains(filterString, StringComparison.OrdinalIgnoreCase))
                     {
                         filterPersonView.PersonList.Add(person);
                     }
                 }
             }
             return View(filterPersonView);
         }
         [HttpPost]
         public IActionResult CreatePerson(CreatePersonViewModel createPerson)
         {
             PeopleViewModel peopleView = new PeopleViewModel();
             PeopleMemory peopleMemory = new PeopleMemory();
             if (ModelState.IsValid)
             {
                 peopleView.FullName = createPerson.FullName;
                 peopleView.City = createPerson.City;
                 peopleView.PhoneNumber = createPerson.PhoneNumber;
                 peopleView.Email = createPerson.Email;
                 peopleView.PersonList = peopleMemory.Read();
                 peopleMemory.Create(createPerson.FullName, createPerson.City, createPerson.PhoneNumber, createPerson.Email);
                 ViewBag.Message = "Successfully added person!";
                 return View("Index", peopleView);
             }
             ViewBag.Message = "Failed to add person" + ModelState.Values;
             return View("Index", peopleView);
         }
         public IActionResult DeletePerson(int id)
         {
             PeopleMemory peopleMemory = new PeopleMemory();
             Person DeletePerson = peopleMemory.Read(id);
             bool status = peopleMemory.Delete(DeletePerson);
             return RedirectToAction("Index");
         }
    }
}

MVC Basics 1/Controllers/PeopleNewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Basics_1.Data;
using MVC_Basics_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    [Authorize(Roles ="Admin, User")]
    public class PeopleNewController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleNewController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult People()
        {
            List<PeopleModel> ListOfPeople = _context.People.ToList();
            return View(ListOfPeople);
        }
        public IActionResult CreatePerson()
        {
            ViewBag.CityID = _context.Cities.Select(a => new SelectListItem
            {
                Text = (a.ID).ToString(),
                Value = (a.ID).ToString()
            }).ToList();
            return View();
        }
        [HttpPost]
        public IActionResult CreatePerson(PeopleModel person)
        {
            if (ModelState.IsValid)
            {
                _context.People.Add(person);
                _context.SaveChanges();
                return RedirectToAction("People");
            }
            return View();
        }
        
        public IActionResult EditPerson(int personId)
        {
            var personData = _context.People.Where(x => x.PersonId == personId).FirstOrDefault();
            if(personData != null)
            {
                ViewBag.CityID = _context.Cities.Select(a => new SelectListItem
                {
                    Text = (a.ID).ToString(),
                    Value = (a.ID).ToString()
                }).ToList();
                TempData["PersonID"] = personId;
                TempData.Keep();
                return View(personData);
             }

            return View();
        }

        [HttpPost]
        public IActionResult EditPerson(PeopleModel person)
        {
            int personId = (int)TempData["PersonID"];
            var personData = _context.People.Where(x => x.PersonId == personId).FirstOrDefault();
            if(personData != null)
            {
                personData.FullName = person.FullName;
                personData.PhoneNumber = person.PhoneNumber;
                personData.Email = person.Email;
                personData.CityID = person.CityID;
                _context.Entry(personData).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("People");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeletePerson(int personId)
        {
            if (personId > 0)
            {
                var personbyId = _context.People.Where(x => x.PersonId == personId).FirstOrDefault();
                if (personbyId != null)
                {
                    _context.Entry(personbyId).State = EntityState.Deleted;
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("People");
        }
    }
}

MVC Basics 1/Views/PeopleNew/CreatePerson.cshtml
@model MVC_Basics_1.Models.PeopleModel

@{
    ViewData["Title"] = "CreatePerson";
}

<h2>CreatePerson</h2>

<h4>PeopleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityID" class="control-label"></label>
                <select asp-for="CityID" class ="form-control" asp-items="ViewBag.CityID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC Basics 1/Views/PeopleNew/EditPerson.cshtml
@model MVC_Basics_1.Models.PeopleModel

@{
    ViewData["Title"] = "EditPerson";
}

<h2>EditPerson</h2>

<h4>PeopleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonId" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityID" class="control-label"></label>
                <select asp-for="CityID" class="form-control" asp-items="ViewBag.CityID"></select>
                <span asp-validation-for="CityID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC Basics 1/Views/PeopleNew/Index.cshtml
@{ ViewData["Title"] = "Index"; }

<h1>People retrived from database </h1>

<ul>
    <li>
        <a class="btn btn-primary" asp-controller="PeopleNew" asp-action="People">People</a>
    </li>
</ul>

MVC Basics 1/Views/PeopleNew/People.cshtml
@model IEnumerable<PeopleModel>
@{ 
    ViewData["Tiltle"] = "People";
}
<h1><b>List of person</b></h1>

<a asp-action="CreatePerson">Create</a>

<table class="table">
    <thead>
        <tr>
            <th>Full Name</th>
            <th>City</th>
            <th>Phone Number</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
        {
        <tr>
            <td>@person.FullName</td>
            <td>@person.CityID</td>
            <td>@person.PhoneNumber</td>
            <td>@person.Email</td>
            <td> @Html.ActionLink("Edit", "EditPerson", new { personId = person.PersonId }) | @Html.ActionLink("Delete", "DeletePerson", new { personId = person.PersonId }) </td>
        </tr>
        }
    </tbody>
</table>