MVC Basics 1/Controllers/CityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC_Basics_1.Data;
using MVC_Basics_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    [Authorize(Roles ="Admin")]
    public class CityController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CityController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Cities()
        {
            List<CityModel> ListOfCities = _context.Cities.ToList();
            return View(ListOfCities);
        }

        public IActionResult CreateCity()
        {
            ViewBag.CountryCode = _context.Countries.Select(a => new SelectListItem
            {
                Text = a.Code, 
                Value = a.Code 
            }).ToList();
            return View();
        }
        [HttpPost]
        public IActionResult CreateCity(CityModel city)
        {
            if(ModelState.IsValid)
            {
                _context.Cities.Add(city);
                _context.SaveChanges();
                return RedirectToAction("Cities");
            }
            return View();
        }
        public IActionResult EditCity(int cityid)
        {
           var CityData = _context.Cities.Where(x => x.ID == cityid).FirstOrDefault();
            if(CityData != null)
            {
                ViewBag.CountryCode = _context.Countries.Select(a => new SelectListItem
                {
                    Text = a.Code,
                    Value = a.Code
                }).ToList();
                TempData["CityID"] = cityid;
                TempData.Keep();
                return View(CityData);
            }
            return View();
        }

        [HttpPost]
        public IActionResult EditCity(CityModel city)
        {
            int cityID = (int)TempData["CityID"];
            var CityData = _context.Cities.Where(x => x.ID == cityID).FirstOrDefault();

            if(CityData != null)
            {
                CityData.Name = city.Name;
                CityData.CountryCode = city.CountryCode;
                CityData.Population = city.Population;
                _context.Entry(CityData).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("Cities");
        }

        public IActionResult DeleteCity(int cityid)
        {
            if(cityid > 0)
            {
                var citybyid = _context.Cities.Where(x => x.ID == cityid).FirstOrDefault();
                if(citybyid != null)
                {
                    _context.Entry(citybyid).State = EntityState.Deleted;
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Cities");
        }

    }
}

MVC Basics 1/Controllers/GuessController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC_Basics_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class GuessController : Controller
    {
        public IActionResult Index()
        {
            GuessModel gs = new GuessModel(this);
            gs.SetRandomNumber();
            return View();
        }
        [HttpPost]
        public IActionResult Index(int number)
        {
            GuessModel gs = new GuessModel(this);
            gs.GetRandomNumber();
            ViewBag.Message = gs.GuessNumber(number);
            return View();
        }
    }
}

MVC Basics 1/Controllers/ReactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Basics_1.Data;
using MVC_Basics_1.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    public class ReactController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ReactController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("/React/People")]
        public IActionResult People()
        {
            return Json(_context.People.ToList());
        }

        [HttpGet]
        public IActionResult Person(int id)
        {
            var person = _context.People
                .Where(p => p.PersonId == id)
                .Include(p => p.City)
                .Include(p => p.City.Country)
                .Include(p => p.PeopleLanguages)
                .FirstOrDefault();

            if (person != null)
            {
                foreach (People_LanguageModel personLanguage in person.PeopleLanguages)
                {
                    personLanguage.Language = _context.Languages.Find(personLanguage.LanguageID);
                }

            }

            return Json(person);
        }

        [HttpDelete]
        public IActionResult DeletePerson(int id)
        {
            if (id > 0)
            {
                var personbyId = _context.People.Where(x => x.PersonId == id).FirstOrDefault();
                if (personbyId != null)
                {
                    _context.Entry(personbyId).State = EntityState.Deleted;
                    _context.SaveChanges();
                }
            }
            return Ok();
        }

        [HttpGet]
        public IActionResult GetCitiesInCountry(string id)
        {
            List<CityModel> cities = _context.Cities.Where(city => city.CountryCode == id).ToList();

            return Json(cities);
        }

        [HttpGet]
        public IActionResult GetFormData()
        {
            var data = new
            {
                countries = _context.Countries.ToList(),
                cities = _context.Cities.ToList()
            };

            return Json(data);
        }


        [HttpPut]
        public IActionResult CreatePerson(CreatePersonViewModel person)
        {
            if (ModelState.IsValid)
            {
                _context.People.Add(new PeopleModel()
                {
                    FullName = person.FullName,
                    CityID = person.CityID,
                    PhoneNumber = person.PhoneNumber,
                    Email = person.Email,
                });
                _context.SaveChanges();

                return Ok();
            }

            return BadRequest();
        }
    }
}

MVC Basics 1/Views/Shared/_AjaxPersonPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<Person>
    <div class="row" style="font-weight: bold; background-color: #96D4D4; font-size: 20px">
        <div class="col-2">
            Person ID
        </div>
        <div class="col-2">
            Full Name
        </div>
        <div class="col-2">
            City
        </div>
        <div class="col-2">
            Phone Number
        </div>
        <div class="col-3">
            Email
        </div>
        <div class="col-1">
            Action
        </div>
    </div>
    @foreach (var person in Model)
    {
        <partial name="_PersonPartial" model="person" />
    }

MVC Basics 1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!-- <img src="/images/logo.png" width="100" height="50">-->
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ekram-ASP.NETCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Projects">Projects</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Patient">Fever Check</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Guess" asp-action="Index">Guess</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="PersonAjax" asp-action="Index">PeopleInAjax</a>
        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PeopleNew" asp-action="Index">PeopleInEntity</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City</a>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="React" asp-action="Index">React</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.ToShortDateString() - Ekram Ahmedin -<a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/PersonScript.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVC Basics 1/Views/Shared/_PersonPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Person

<div class="row" style="background-color: #96D4D4; font-size: 20px">
    <div class="col-1">
        @Model.PersonId
    </div>
    <div class="col-3">
        @Model.FullName
    </div>
    <div class="col-2">
        @Model.City
    </div>
    <div class="col-2">
        @Model.PhoneNumber
    </div>
    <div class="col-3">
        @Model.Email
    </div>
    <div class="col-1">
        <a href="#" onclick="location.href ='@Url.Action("DeletePerson", "People", new { id = Model.PersonId })'">Delete</a>
    </div>
</div>