MVC Basics 1/Models/CountryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Models
{
    public class CountryViewModel
    {
        public IEnumerable <CountryModel> Countries { get; set; }
    }
}

MVC Basics 1/Models/CreateCountryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Models
{
    public class CreateCountryViewModel
    {
        [Required]
        [Display(Name = "Country Name")]
        [MaxLength(100)]
        public string CountryName { get; set; }
    }
}

MVC Basics 1/Controllers/CountryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Basics_1.Data;
using MVC_Basics_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Basics_1.Controllers
{
    [Authorize(Roles="Admin")]
    public class CountryController : Controller
    {
        private readonly ApplicationDbContext _context;
        
        public CountryController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Countries()
        {
            List<CountryModel> ListOfCountries = _context.Countries.ToList();
            return View(ListOfCountries);
        }

        public IActionResult CreateCountry()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateCountry(CountryModel country)
        {
            if (ModelState.IsValid)
            {
                _context.Countries.Add(country);
                _context.SaveChanges();
                return RedirectToAction("Countries");
            }
            return View();
        }
        public IActionResult EditCountry(String countryCode)
        {
           var Countrydata = _context.Countries.Where(x => x.Code == countryCode).FirstOrDefault();
            if (Countrydata != null)
            {
                TempData["CountryCode"] = countryCode;
                TempData.Keep();
                return View(Countrydata);
            }
            return View();
        }

        [HttpPost]
        public IActionResult EditCountry(CountryModel country)
        {
            String countryCode = (string)TempData["CountryCode"];
            var Countrydata = _context.Countries.Where(x => x.Code == countryCode).FirstOrDefault();
            if(Countrydata!=null)
            {
                Countrydata.Name = country.Name;
                Countrydata.Continent = country.Continent;
                Countrydata.Population = country.Population;
                _context.Entry(Countrydata).State = EntityState.Modified;
                _context.SaveChanges();
            }
            return RedirectToAction("Countries");
        }
        
         public IActionResult DeleteCountry(string countryCode)  
          {  
             if (countryCode != null || countryCode != "")  
             {
                var countrybyCode = _context.Countries.Where(x => x.Code == countryCode).FirstOrDefault();
        
                if (countrybyCode != null)  
                  {  
                     _context.Entry(countrybyCode).State = EntityState.Deleted;  
                     _context.SaveChanges();  
                  }  
              }  
              return RedirectToAction("Countries");  
           } 
         
         
    }
}

MVC Basics 1/Views/Country/Countries.cshtml
@model IEnumerable<CountryModel>
@{
    ViewData["Title"] = "Countries";
}

<h1><b>List of Countries</b></h1>

<a asp-action="CreateCountry">Create</a>

<table class="table">
    <thead>
        <tr>
            <th> Country Code</th>
            <th>Name</th>
            <th>Continent</th>
            <th>Population</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var country in Model)
        {
            <tr>
                <td>@country.Code</td>
                <td>@country.Name</td>
                <td>@country.Continent</td>
                <td>@country.Population</td>
                <td> @Html.ActionLink("Edit", "EditCountry", new { countryCode = @country.Code }) | @Html.ActionLink("Delete", "DeleteCountry", new { countryCode = @country.Code }) </td>
            </tr>
        }
    </tbody>
</table>

MVC Basics 1/Views/Country/CreateCountry.cshtml
@model MVC_Basics_1.Models.CountryModel

@{
    ViewData["Title"] = "CreateCountry";
}

<h2>CreateCountry</h2>

<h4>CountryModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCountry">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continent" class="control-label"></label>
                <input asp-for="Continent" class="form-control" />
                <span asp-validation-for="Continent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC Basics 1/Views/Country/EditCountry.cshtml
@model MVC_Basics_1.Models.CountryModel

@{
    ViewData["Title"] = "EditCountry";
}

<h2>EditCountry</h2>

<h4>CountryModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCountry">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Code" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continent" class="control-label"></label>
                <input asp-for="Continent" class="form-control" />
                <span asp-validation-for="Continent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Population" class="control-label"></label>
                <input asp-for="Population" class="form-control" />
                <span asp-validation-for="Population" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVC Basics 1/Views/Country/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Country</h2>

<ul>
    <li>
        <a class="btn btn-primary" asp-controller="Country" asp-action="Countries">Country</a>
    </li>
</ul>